### ISSUE TITLE
Inference time?

### ISSUE THREAD

**Issue by mrdbourke** [matyasbohacek/xgboost-vs-gpt4#2]
Hey there, 

Love this work! I'm also a big fan of using pre-LLM style models for problems which require far less compute resources.

Do you have any data on the inference time per sample? 

E.g. if there are 1,000 samples, how long does each model take to perform inference?

I'd assume XGBoost running on the right hardware is faster than an API call to GPT4? Is this true?

**Comment by maty-bohacek** [comment]
Thanks for the comment, @mrdbourke! I unfortunately don't have hard data for this (I tried digging this up but with no luck). Anecdotally: yes, I recall the experiment running faster for sure.

Sorry that I can't be more precise, and hope you still find this valuable. Feel free to post your own findings here if you decide to study this in a bit more detail.
